### ISSUE TITLE
Scoped imports breaking build

### ISSUE THREAD

**Issue by BrandonBlanchard** [u12206050/react-gutenberg#2]
![image](https://user-images.githubusercontent.com/1466960/72565997-ddab4f00-3867-11ea-83b4-64fcb50f5492.png)

The newly added scoped imports are breaking the build. Any reason not to use relative imports?

**Comment by BrandonBlanchard** [comment]
I love what you've done here btw, this is a much more elegant version of what I had hacked together :D

**Comment by u12206050** [comment]
Hey, sorry didnt really think of that. You are welcome to make a pull request.

**Comment by BrandonBlanchard** [comment]
Thanks for the quick merge!
