### ISSUE TITLE
Feature Request to support additional props to the blocks

### ISSUE THREAD

**Issue by umakantozy** [u12206050/react-gutenberg#4]
I have been extensively using the to build a website which has admin as Wordpress which creates page using gutenberg blocks. Although I'm in need of future which could be generic and might be useful to others as well.

Below is the example of the feature request.

```
<div>
   <WPGBlocks blocks={items} onClick={callback} otherProp={false} />
</div>
```
onClick and otherProp are optional extra props which can be passed to `items` other than attrs, innerBlocks, name...etc.

WPGBlocks could read rest props excluding mapToBlock and blocks like

```
const extraProps = lodash.omit(props, ['mapToBlock', 'blocks])
```
extraProps can be then further as props while rendering the blocks as follows
```
<TheBlock blockName={blockName} attrs={attrs} innerBlocks={innerBlocks} innerHTML={innerHTML} {...extraProps} />
```

I'm not sure if this the right place to request a feature. Can we please have a such a feature? This will give more customisation where anyone needs integration of Wordpress blocks in general page which also needs to talk to these blocks.

Thanks

**Comment by u12206050** [comment]
I'm afraid I don't follow quite what you need. Do you have an example use case that could explain the use of this better. Also, how would you define the function required by the onClick prop?

**Comment by umakantozy** [comment]
In simple I would want Blocks to also take custom arguments (and not just arguments coming in from Wordpress), to make it more customisable. Imagine I have I'm adding wordpress page as subpart of large page which have some other custom elements coming from elsewhere.

I have tried to put below example as easy as just to demonstrate what I'm talking of.

```
import React, {useState} from 'react';
import {ListItem} from 'blocks';

const SomeComponent = ({page}) => {
  const theme = 'red;
  const [list, setList] = useState([]);

  const onBlockSelected = (id) => {
    let listProper = list.concat();
    listProper.push(id)
    setList(listProper)
  };

  return (
    <div>
      <p>Selected items are: {list} </p>
      <ul>
        <WPGBlocks blocks={page.blocks} mapToBlock={(name) => {
          switch (name) {
            case 'my-blocks/list-item':
              return ListItem;

            default:
              return null;
          }
        }} onClick={onBlockSelected theme={theme} />
      </ul>
    </div>
  );
};

SomeComponent.getInitialProps = async () => {
  const res = await fetch(`http://www.mywordpress.com/wp-json/wp/v2/pages/?slug=somepage`);
  const json = await res.json();
  return {page: json[0]};
};

export default SomeComponent;
```

Ideally that listing the selected items could also be part of blocks. Well it could it be. But this is just an example. One could have some other use cases to pass props to block. Say like theme color of the page (page is not Wordpress page) ?

**Comment by u12206050** [comment]
Well, you could just merge your custom block data into the `blocks` array that comes from WP, matching it to the same format. And then it will render your non WP custom blocks as well.

**Comment by u12206050** [comment]
The problem with such a global parameter is that it would then be sent down to all blocks, in such a case it would then be better to just have the variable in a store state.
